[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = [
    "apt-get update",
    "apt-get install -y libicu-dev zlib1g-dev libzip-dev",
    "docker-php-ext-install intl zip",
    "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
